#!/bin/sh

stat=true
if [ "$1" = "-p" ]; then
    stat=false
    shift 1
fi

cmd="git diff ${2:-HEAD}"
(
    cd "$1"
    if [[ $stat == true ]]; then
        $cmd | diffstat | grep -v "only$"
    else
        $cmd
    fi
)
